---@meta

---@alias CraftSim.Event
--- Fired when the SchematicForm on either the CraftingPage or OrdersPage is initialized for a new recipe.
--- args: recipeInfo RecipeInfo
---| "CRAFTSIM_OPEN_RECIPE_INFO_UPDATED"
--- Fired once profession operation-info data has fully loaded and the profession is ready for use.
--- args: none
---| "CRAFTSIM_PROFESSION_INITIALIZED"
--- Fired after a profession is opened and all CRAFTING_DETAILS_UPDATE data is available.
--- args: professionInfo ProfessionInfo, selectedTab CraftSim.PROFESSIONS_TAB, isLogin boolean, isReload boolean
---| "CRAFTSIM_PROFESSION_OPENED"
--- Fired when the initial recipe's RecipeInfo becomes available after a profession opens.
--- args: recipeInfo RecipeInfo
---| "CRAFTSIM_RECIPE_INFO_INITIALIZED"
--- Fired when Simulation Mode is activated for the currently visible recipe.
--- args: none
---| "CRAFTSIM_SIMULATION_MODE_ENABLED"
--- Fired when Simulation Mode is deactivated (e.g. switching to a recraft/salvage recipe).
--- args: none
---| "CRAFTSIM_SIMULATION_MODE_DISABLED"
--- Fired whenever a reagent allocation changes while Simulation Mode is active.
--- args: none
---| "CRAFTSIM_SIMULATION_MODE_ALLOCATION_CHANGED"
--- Fired when the active RecipeData should be re-evaluated by all listening modules (reagent change, concentration toggle, sim mode update, etc.).
--- This is emitted by components that mutate recipe-relevant state.
--- args: recipeData CraftSim.RecipeData?
---| "CRAFTSIM_RECIPE_DATA_MODIFIED"
--- Fired after CraftSim.MODULES relays CRAFTSIM_RECIPE_DATA_MODIFIED and has prepared the updated RecipeData for listeners.
--- args: recipeData CraftSim.RecipeData?
---| "CRAFTSIM_RECIPE_DATA_UPDATED"
--- Fired when the player clicks one of the profession frame tabs (Recipe, Spec, Crafting Orders).
--- args: tab CraftSim.PROFESSIONS_TAB
---| "CRAFTSIM_PROFESSION_TAB_CLICKED"
--- Fired immediately after CraftRecipe / SalvageRecipe is called and CraftSim has built the RecipeData for the craft in progress.
--- args: recipeData CraftSim.RecipeData
---| "CRAFTSIM_CRAFT_RECIPE_DATA_PREPARED"
--- Fired once crafting orders for the current profession have been silently preloaded in the background.
--- args: none
---| "CRAFTSIM_CRAFTING_ORDERS_PRELOADED"
--- Fired when the crafting-orders OrderView panel is hidden.
--- args: none
---| "CRAFTSIM_ORDER_VIEW_CLOSED"
--- Fired when a long CraftQueue process (work orders, first crafts, or craft lists) finishes.
--- args: queueType "WORK_ORDERS"|"FIRST_CRAFTS"|"CRAFT_LISTS"
---| "CRAFTSIM_CRAFTQUEUE_QUEUE_PROCESS_FINISHED"
--- Fired when a module frame is closed by the user.
--- args: moduleID CraftSim.ModuleID
---| "CRAFTSIM_MODULE_CLOSED"
--- Fired when a module frame is opened by the user.
--- args: moduleID CraftSim.ModuleID
---| "CRAFTSIM_MODULE_OPENED"
--- Fired when a module frame is minimized by the user.
--- args: moduleID CraftSim.ModuleID
---| "CRAFTSIM_MODULE_MINIMIZED"
--- Fired when a module frame is maximized/restored by the user.
--- args: moduleID CraftSim.ModuleID
---| "CRAFTSIM_MODULE_MAXIMIZED"
--- Fired when a CraftSim setting is saved via the WoW Settings panel.
--- args: optKey CraftSim.GENERAL_OPTIONS, value any
---| "CRAFTSIM_SETTINGS_UPDATED"
--- Fired when the set of active tracked craft buffs changes (buff added or removed).
--- args: none
---| "CRAFTSIM_CRAFT_BUFFS_UPDATED"
--- Fired once the Craft Queue module frame exists so the queue recipe editor can anchor and create its popup (parent/anchor only; no queue tab reference).
--- args: parent frame, anchorParent Region (typically the Craft Queue GGUI frame's `.frame`)
---| "CRAFTQUEUE_EDIT_RECIPE_HOST_READY"
--- Fired to open the queue recipe editor for a queue row (listener owns the editor frame).
--- args: craftQueueItem CraftSim.CraftQueueItem
---| "CRAFTQUEUE_EDIT_RECIPE_REQUEST_OPEN"
